### ISSUE TITLE
Changes in connectivity kill the web socket without reconnecting it

### ISSUE THREAD

**Issue by CallMeSH** [sendbird/sendbird-sdk-flutter#10]
Hello!

We are currently implementing the SDK in our app and we have noticed a problem on the way the connectivity is handled.
Here is a way to reproduce the problem:

1. On Android, start the app and wait for the SDK to be connected
2. Go into Airplane mode without leaving the app
3. Close the notification tray
4. The Websocket connection should be lost
5. Reopen the notification tray and deactivate Airplane mode
6. Close the tray

In this state the SDK does not start a reconnection automatically and only going to background and back to foreground fixes the issue.

From my own researches in the code, I think the issue is located in `sendbird_sdk_internal.dart`:
```dart
  void _listenConnectionEvents() {
    //NOTE: do not run connectivity on test
    final isTest = Platform.environment['FLUTTER_TEST'] == 'true';
    if (!isTest) {
      _connectionSub = Connectivity()
          .onConnectivityChanged
          .listen((ConnectivityResult result) {
        switch (result) {
          case ConnectivityResult.none:
            logger.i('connection has been lost');
            break;
          case ConnectivityResult.mobile:
          case ConnectivityResult.wifi:
            if (_connectionResult == ConnectivityResult.none &&
                _state.sessionKey != null) {
              reconnect(reset: true);
            }
        }
      });
    }
  }
```

This condition seems a little weird as I would expect the `ConnectivityResult.none` switch case to cleanup the state as going to background does.
And the second case can never happen as it is running two conflicting tests. (`_connectionResult` can't be equal to `ConnectivityResult.none` if it is either `ConnectivityResult.mobile` or `ConnectivityResult.wifi`.

I hope this will help, thanks in advance.

**Comment by intoxicated** [comment]
Hi @CallMeSH I think I missed 

```
_connectionResult = result; 
```
at the end of switch statement (to save previous connectionResult). Would you try to insert above line after switch statement? I will fix and release patch version once you confirm the fix.

**Comment by CallMeSH** [comment]
Hello, 

After testing your suggestion, the problem is indeed fixed!
I think you can ho ahead and proceed with the patch!

Thanks! 👌

**Comment by intoxicated** [comment]
Thank you for the confirmation! Will patch this issue on next release.

**Comment by intoxicated** [comment]
released
