### ISSUE TITLE
change connectivity to connectivity_plus

### ISSUE THREAD

**Issue by Fr099y** [sendbird/sendbird-sdk-flutter#12]
The last version of Android Studio requires Java 11 or the upper version. Connectivity plugin deprecated and error on the build. It will be fixed when changed to connectivity_plus. Please change the connectivity plugin to connectivity_plus.

Build error:` **connectivity:compileDebugJavaWithJavac**`

I created a pull request
#13

**Comment by intoxicated** [comment]
this has been patched
