### ISSUE TITLE
lastMessage in channel is null as long as the member state is 'invited'

### ISSUE THREAD

**Issue by BghinC** [sendbird/sendbird-sdk-flutter#15]
Hello,

We're working with the invitation system and we have a problem regarding the `lastMessage` property of a channel.

When we retrieve a list of channel the `lastMessage` property is set if we are the one who sent the invitation or we have accepted the invitation. However, the property is `null` as long as we have not accepted the invitation and our `state` in the channel is `invited`.

Is it the expected behaviour?

We would like to show the last message even if we have not joined the channel yet. And, even with the `invited` state we can retrieve all the channel messages. That's why I don't know if hiding the `lastMessage` property is wanted in this case and if it is, what is the reason?

Thank you!

**Comment by intoxicated** [comment]
@BghinC for first question, yes I believe it is expected behavior. Group channel is private in default and cannot see messages by users who are not join yet. If you want to make it visible to everyone, you have to make a group channel as public.

**Comment by BghinC** [comment]
@intoxicated Thank you for you reply.

If I'm invited to a channel and I did not joined it yet, I can retrieve all the messages sent in this channel even if the group channel is private.
That's why I don't understand why when we fetch the channels list, the last message is not set.

If you say I cannot see messages if I did not joined the channel yet (invited state), we should not be able to retrieve all the messages in the channel?

**Comment by intoxicated** [comment]
`If I'm invited to a channel and I did not joined it yet, I can retrieve all the messages sent in this channel even if the group channel is private.` << let me check this is right behavior

**Comment by intoxicated** [comment]
btw would you check for me one thing? you said you were able to retrieve messages while you did not join, did you manually turn off `setChannelInvitationPreference` to `false` ?

**Comment by CallMeSH** [comment]
Hello @intoxicated,

For our use case, the invitations are not auto-accepted by the users, they need to manually accept invitations.
As @BghinC explained, as an invited user you get access to all the messages inside the channel, but in a message query list you don't get the last message which is a bit odd.

Thanks!

**Comment by intoxicated** [comment]
I just run with following scenario in a test case,

1. create 4 users and created a channel with first three users. 
2. send arbitrary messages to the channel
2. set last users `setChannelInvitationPreference` to `false`
3. invite last user to the channel
4. connect with last user
4. refresh previous channel and confirmed my state is `invited`
5. fetched messages from `getMessagesByTimestamp` or using `PreviousMessageListQuery` -> result is empty 

and I cannot reproduce your case.

**Comment by CallMeSH** [comment]
Hello,

We can reproduce it with this process:
1.  Create two users having `setChannelInvitationPreference` to false
2. Create a private group between user `a` and user `b`, setting user `a` as the inviter
3. User `b` can see a channel and fetch the messages with `getMessagesByTimestamp` or `PreviousMessageListQuery` and has the state `invited`.
4. User `a` can see the channel in the channel list with the last message but user `b` can't.

**Comment by BghinC** [comment]
Hi @intoxicated,

Do you have any update on the issue?

Thanks

**Comment by intoxicated** [comment]
Sorry for delayed response. I'm kinda packed right now and couldn't reproduce this yet. I will look into it more this week.

**Comment by BghinC** [comment]
Hi @intoxicated,

We would like to publish a new version of our apps and this issue is quite annoying for us. Did you manage to reproduce the issue?

**Comment by intoxicated** [comment]
Would you please show me exact code you use for testing? I still cannot reproduce the issue. 

I tested with this scenario.

1. Creates A, B users
2. Sets channel invitation preference to `false` for B
2. Creates a channel with A and send multiple messages
3. Connects with User B
4. Attempts to fetch messages from the channel
5. got 0 messages

Like I said, this is expected behavior afaik, and if you think be able to fetch from not joined channel is annoying then you can do workaround to avoid fetching message by checking `memberState` as `joined` only. And it would be helpful if you can explain to me in detail how you implement the use case you mention above.

**Comment by intoxicated** [comment]
Additionally, setting logger option to verbose and share console result would much help too

**Comment by intoxicated** [comment]
@BghinC do you have any progress?

**Comment by BghinC** [comment]
Hi,

I did not have time to work on the issue this week, we made a workaround to replace the last message. I might have more time in the end of next week to give you more info & some code or a minimal reproduction repository.
