### ISSUE TITLE
Incorrect connection status after disconnection

### ISSUE THREAD

**Issue by BghinC** [sendbird/sendbird-sdk-flutter#18]
Hello,

I'm facing an issue concerning the connection status.
The user status stays online after disconnecting from Sendbird and reconnecting.

Steps to reproduce:
- Connect to Sendbird using `sendbirdInstance.connect`
- Your connection status should be online
- At this step you can try to switch the app in background/foreground to check the connection status switch between offline and online
- Disconnect from Sendbird using `sendbirdInstance.disconnect`
- Your connection status should be online
- Reconnect to Sendbird using `sendbirdInstance.connect`
- Your connection status should be online
- Switch the app between background and foreground. You should see the connection status staying online

To fix the connection status you have to kill the app.

**Comment by intoxicated** [comment]
I'm not sure I don't understand the problem here, would you please clarify the issue? I believe we do not support liveness of connection status, so it has to be fetched from either user list if you want to use it with up to date information

**Comment by BghinC** [comment]
Hello,

You do not support liveliness of connection status, that's right. We fetch all users to keep an updated list of users with their connection status.

I made more tests and, in fact, the connection status into the Sendbird dashboard is still **online** after `connect` then `disconnect` and put the app in background. However, when you `disconnect` another time the status is back **offline**.

So the problem is when you `connect` then `disconnect` to the same account, the connection status is not updated when the app switch to background.

**Comment by intoxicated** [comment]
got it, hmmm that's weird. I will investigate deeper

**Comment by intoxicated** [comment]
I found a issue and will fix on next patch! Thanks for reporting

**Comment by intoxicated** [comment]
`3.1.3` has been released. Feel free to reopen if you still see this problem.
