### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by w3ggy** [sendbird/sendbird-sdk-flutter#19]
Are there any plans for Flutter web support?

Or it is just a pure Dart SDK and can be launched everywhere?
In such a case current description is confusing me 😅 

<details>

![image](https://user-images.githubusercontent.com/12301508/131865547-6d048344-6583-44f8-b523-47da1bf42f8e.png)

</details>

I see that package uses `import 'dart:io';` in some files and it looks like there is no way to use it on the web?

**Comment by intoxicated** [comment]
Hi @w3ggy unfortunately we do not support web yet but I'm planning to add web support this year (I wish I can add this more faster 😢)

**Comment by intoxicated** [comment]
@w3ggy web support will be included in near future! Thanks for your patient

**Comment by aquilarafa** [comment]
What is needed for the sdk starts working on web?

**Comment by iampato** [comment]
We need this.
It is like a do or die .. please

**Comment by intoxicated** [comment]
@iampato `3.1.9` will be include web support fyi.
