### ISSUE TITLE
Dependencies is outdated

### ISSUE THREAD

**Issue by ZorianaIvaniuk** [sendbird/sendbird-sdk-flutter#2]
Depends on http ^0.12.0, the newest version http: ^0.13.2, depends on  shared_preferences ^0.5.12+2 the newest version shared_preferences ^2.0.1  
You're doing great with sendbird_sdk for flutter 
Please update these dependencies because it needs to override almost all dependencies in my project to get this package

**Comment by intoxicated** [comment]
Those dependencies are not suitable for current implementation due to null safety feature on Dart 2.12 which is shipped with Flutter 2. We are working on migration for null safety.

**Comment by Jagadeesh09-dev** [comment]
Even i have been facing the same issue and i want to know the release date of new version

**Comment by intoxicated** [comment]
@Jagadeesh09-dev hi, I believe null-safety update will be around June. Thanks for your patient!

**Comment by intoxicated** [comment]
@Jagadeesh09-dev @ZorianaIvaniuk I just released `3.0.14-nullsafety` before we go for official release. Feel free to install it and let me know if you guys have any problems.

**Comment by intoxicated** [comment]
We decided to raise minor version so official version will be `3.1.0` and prerelease `3.1.0-nullsafety`
