### ISSUE TITLE
PUSH Notifications Huawei

### ISSUE THREAD

**Issue by jjsebastianfuertes** [sendbird/sendbird-sdk-flutter#22]
Hi,

I'm connecting push notifications with HMS. although I get this response. 

RESPONSE: Platform API Error
CODE: 400404

-------
** Plugins Version

  huawei_push: 5.1.1+301
  sendbird_sdk: 3.1.3

---- 

Steps used

* to configure HMS credentials in sendbird dashboard;

```
 await _sendBird.registerPushToken(
        type: PushTokenType.hms,
        token:  token,
      );
```

any idea what can be happening?

**Comment by intoxicated** [comment]
have you done hms configuration correctly? https://sendbird.com/docs/chat/v3/android/guides/push-notifications#2-push-notifications-for-hms-3-step-1-generate-app-id-and-app-secret-for-hms

**Comment by jjsebastianfuertes** [comment]
Yes, do I also need to integrate native code?
<img width="1280" alt="Screen Shot 2021-09-20 at 5 24 31 PM" src="https://user-images.githubusercontent.com/26838420/134084465-d7d2f20d-1529-41f9-aa25-77d66ce3eadf.png">

**Comment by intoxicated** [comment]
Ah, I see, I will investigate and fix the issue on next release (probably at the end of this week). Thank you for reporting

**Comment by intoxicated** [comment]
`3.1.4` has been released. Feel free to reopen if the problem still occurs
