### ISSUE TITLE
Get Session Key when connect to server

### ISSUE THREAD

**Issue by RicharC293** [sendbird/sendbird-sdk-flutter#24]
We have the problem when user login to app and connect user. 
The following message was intercepted: Not authorized. "Session-Key doesn't match user_id
The conclusion to the problem is when user connect to sendbird server this not obtain the correct session key.
The snipet code is following 
To init sendbird in main.dart

`  void _sendBirdInit() {
    try {
      _sendBird = SendbirdSdk(appId: Flavor.sendbird);
      _sendBird.addChannelEventHandler("channel_list_view_shopper", this);
    } catch (err) {
      debugPrint("SENDBIRD_INIT: $err");
    }
  }`

To connect user when login is success

`Future<void> connectUserToSendBirdServer(
      {UserModel user, TokensModel token}) async {
    try {
      await _sendBird.connect(user?.user?.email);
      await _sendBird.updateCurrentUserInfo(
        nickname:
            "${user?.user?.firstName ?? ""} ${user?.user?.lastName ?? ""}",
        fileInfo:
            FileInfo.fromUrl(mimeType: "image/jpeg", url: user?.picture ?? ""),
      );
    } catch (err) {
      RegularException(where: "CONNECT_USER", message: "${err.message}");
    }
  }`

After this, get the list of channels 

`Future<void> loadChannelList() async {
    try {
      query = GroupChannelListQuery()
        ..order = GroupChannelListOrder.latestLastMessage
      _groupChannels = await query.loadNext();
      notifyListeners();
    } catch (err) {
      throw RegularException(where: 'LOAD_CHANNEL_LISTS', message: err.message);
    }
  }`

Print this message Not authorized. "Session-Key doesn't match user_id

For some reason the session key corresponding to this connection is not being obtained.

Sendbird SDK 
sendbird_sdk: ^3.1.5
Flutter Doctor:
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [VersiÃ³n 10.0.19042.1237], locale es-EC)
    • Flutter version 2.5.0 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (3 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\tipti\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Users\tipti\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] VS Code (version 1.60.2)
    • VS Code at C:\Users\tipti\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM G960U1 (mobile) • 5a58554858563398   • android-arm64  • Android 10 (API 29)
    • LM X525 (mobile)   • LMX525USUKZP5D9PE6 • android-arm    • Android 10 (API 29)
    • Chrome (web)       • chrome             • web-javascript • Google Chrome 93.0.4577.82
    • Edge (web)         • edge               • web-javascript • Microsoft Edge 94.0.992.31

• No issues found!

**Comment by RicharC293** [comment]
Thanks for your answer @intoxicated , but I have an impediment when implementing more than one event notifier to the same class.
For example:
`class Chat
      with ChangeNotifier, ChannelEventHandler, ConnectionEventHandler {
    }`

The behavior I get is:
1. Notifications of type ChannelEventHandler are duplicated.
2. Notification of type ConnectionEventHandler is not listened.
Is this behavior as expected? 

I was found this example in your repo: [Example]( https://github.com/sendbird/Sendbird-Flutter/blob/61508a52e6869772d92eea646196a538bfd289db/lib/screens/channel/channel_view_model.dart#L20 )
But this is not implemented yet.
[Example](https://github.com/sendbird/Sendbird-Flutter/blob/61508a52e6869772d92eea646196a538bfd289db/lib/screens/channel/channel_view_model.dart#L490 )

**Comment by intoxicated** [comment]
let me check and will get back to you

**Comment by intoxicated** [comment]
did you register listener properly?

```
sendbird.addChannelEventHandler('channel_listener', this);
sendbird.addConnectionEventHandler('connection_listener', this);
```

**Comment by intoxicated** [comment]
I suspect that the reason you get duplicate notification for channel event is because you registered object with add channelEventHandler twice

**Comment by intoxicated** [comment]
I will close this issue since you posted the question at https://community.sendbird.com/t/add-connectioneventhandler/3281/2
