### ISSUE TITLE
Make possible to set a specific userId for registerPushToken and unregisterPushToken API methods

### ISSUE THREAD

**Issue by letsar** [sendbird/sendbird-sdk-flutter#27]
For the moment if we want to register a push token to multiple users, we have to connect each user and then register the push token.
`UserPushTokenRegisterRequest` and `UserPushTokenUnregisterRequest` accept a userId but the parent methods, `registerPushToken` and `unregisterPushToken` don't have a `userId` parameter, so it's always the one of the currently connected user which is taken.
It would be better to let the developer chose if they want to register/unregister for the connected user or a specific one.

**Comment by intoxicated** [comment]
@letsar would you elaborate use case? You can't register push token without calling connect at the moment, and thats because our premises is a device can be used only for a single user.
