### ISSUE TITLE
deprecated packages

### ISSUE THREAD

**Issue by ashwin31** [sendbird/sendbird-sdk-flutter#29]
please update packages

for example device_info is deprecated and device_info_plus is released in it's place.
and shared_preferences too.

**Comment by intoxicated** [comment]
@ashwin31 will do. Thanks for reporting

**Comment by intoxicated** [comment]
shared_preference is not deprecated btw https://pub.dev/packages/shared_preferences

**Comment by jjsebastianfuertes** [comment]
hi, can you upgrade connectivity_plus to 2.2.0 they stop using a deprecated method registerWith (of Android v1 embedding)

**Comment by intoxicated** [comment]
@jjsebastianfuertes We will review our dependencies and will update accordingly soon! Thanks for the report.

**Comment by intoxicated** [comment]
@jjsebastianfuertes will update package soon
