### ISSUE TITLE
Sound null safety

### ISSUE THREAD

**Issue by Truba** [sendbird/sendbird-sdk-flutter#3]
Flutter 2.0 requires sound null safety.
Can you please add support for it.

**Comment by intoxicated** [comment]
Its not a requirement, you can still run with --no-sound-null-safety flag. We are currently wip on migration.

**Comment by Truba** [comment]
Hi @intoxicated , ty for the quick response, awesome that it's already in progress. Keep on the great work 🎉

**Comment by intoxicated** [comment]
@Truba Just released `3.0.14-nullsafety` in case you need to use before we go for official release.

**Comment by intoxicated** [comment]
We decided to raise minor version so official version will be `3.1.0` and prerelease `3.1.0-nullsafety`
