### ISSUE TITLE
v3.1.9 BadRequestError - "message_ts" must be a number (int)., code: 400101

### ISSUE THREAD

**Issue by aquilarafa** [sendbird/sendbird-sdk-flutter#32]
The sdk passes a `message_ts` to the http request with an invalid value.

My code is almost the same as the documentation.
```
final listQuery = PreviousMessageListQuery(
        channelType: ChannelType.group,
        channelUrl: CHANNEL_URL,
    )
    ..limit = LIMIT
    ..reverse = REVERSE
    ...

try {
    final messages = await listQuery.loadNext();
} catch (e) {
}
```
But this exception is thrown
![Captura de Tela 2022-02-15 às 09 12 41](https://user-images.githubusercontent.com/33739544/154061029-e57a6cda-fd82-4574-9076-e7151a6411ed.png)

It is working using the `getMessagesByTimestamp` passing `DateTime.now().millisecondsSinceEpoch`
```
try {
    final params = MessageListParams()
        ..isInclusive = false
        ..previousResultSize = 20
        ..reverse = true
        ..messageTypeFilter = MessageTypeFilter.all
        ..customType = 'custom';

    final messages = await groupChannel.getMessagesByTimestamp(
        DateTime.now().millisecondsSinceEpoch, params: params
    );
} catch (e) {
}
```
`PreviousMessageListQuery.loadNext()` timestamp usage should be the cause.

**Comment by intoxicated** [comment]
could you try 3.1.10 ?

**Comment by aquilarafa** [comment]
Sorry it took this long. Tested. It's working fine.
