### ISSUE TITLE
BadRequestError loading group channel from ticket

### ISSUE THREAD

**Issue by aquilarafa** [sendbird/sendbird-sdk-flutter#34]
Hello,

We created a ticket using Platform API but the flutter sdk fails to load GroupChannel from channelUrl value.
The ticket is not listed on dashboard also.

BadRequestError after creating a  ticket and trying to load `GroupChannel.getChannel(url)`
```
{
code:400201
message:""Channel" not found."
}
```

Any ideas?

**Comment by intoxicated** [comment]
@aquilarafa if its not on dashboard then `channel not found` is probably correct. Do you have url for group channel?

**Comment by aquilarafa** [comment]
I receive a valid GroupChannel url from ticker endpoint response.
If I try to load this GroupChannel then a BadRequestError is shown.

**Comment by aquilarafa** [comment]
It seems that is an error on desk module on their side.
After some months of back and forth communication with Sendbird Support they couldn't solve this. Hope our backend team can make some workaround for this issue.

**Comment by aquilarafa** [comment]
This happens with old tickets for a user

**Comment by aquilarafa** [comment]
Closing this issue since this not be something related to the Flutter SDK.
