### ISSUE TITLE
ConnectionRequiredError - Once toggle the internet connectivity getting ConnectionRequiredError for flutter sendbird

### ISSUE THREAD

**Issue by jaymungara-solutelabs** [sendbird/sendbird-sdk-flutter#35]
Hello,

My sendbird chat is working fine, following as per the sample sendbird for flutter.

But, when I try to toggle the internet connection and try to send the message I get an error log like,

```
Instance of 'ConnectionRequiredError'
      #0      ConnectionManager.readyToExecuteWSRequest (package:sendbird_sdk/managers/connection_manager.dart:61:7)
      #1      CommandManager.sendCommand (package:sendbird_sdk/managers/command_manager.dart:114:31)
      #2      GroupChannelRead.markAsRead (package:sendbird_sdk/core/channel/group/group_channel_read.dart:17:27)
```
      
      Can you please look in to this?

**Comment by intoxicated** [comment]
could you elaborate `toggle the internet connection` ? does that mean you turn off the connection?

**Comment by jaymungara-solutelabs** [comment]
Yes toggle the internet connection => Turning off the internet connection

**Comment by RicharC293** [comment]
Same issue, this is logs:

I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Stop socket ping
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 connection has been lost
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 connection has been lost
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 going foreground
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 attempting to reconnect from foreground
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 try to reconnect
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Attempting to connecting with shopper_ecuador@test.com
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): RECOONECTING.... 
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Setting access token null
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 websocket connecting.. 
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Start socket ping
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/Timeline(16541): Timeline: Activity_idle id: android.os.BinderProxy@59b48dd time:115358153
I/flutter (16541): [Sendbird][E] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][E] │ ⛔ Websocket Error:WebSocketChannelException: WebSocketChannelException: SocketException: Failed host lookup: 'xx-11111111-4bce-4320-85ef-f9977f235e04.sendbird.com' (OS Error: No address associated with hostname, errno = 7)
I/flutter (16541): [Sendbird][E] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][E] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][E] │ ⛔ login timeout
I/flutter (16541): [Sendbird][E] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 logout
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (16541): ON_RECONNECTION_CANCELED
I/flutter (16541): 
I/flutter (16541): #0      _HomeScreenState.crashlyticLogger (package:tipti_shopper/features/home/home_screen.dart:131:18)
I/flutter (16541): #1      _HomeScreenState.onReconnectionCanceled (package:tipti_shopper/features/home/home_screen.dart:161:5)
I/flutter (16541): #2      EventManager.notifyReconnectionCanceled.<anonymous closure> (package:sendbird_sdk/managers/event_manager.dart:361:15)
I/flutter (16541): #3      Iterable.forEach (dart:core/iterable.dart:325:35)
I/flutter (16541): #4      EventManager.notifyReconnectionCanceled (package:sendbird_sdk/managers/event_manager.dart:360:32)
I/flutter (16541): #5      SendbirdSdkInternal.logout (package:sendbird_sdk/sdk/internal/sendbird_sdk_internal.dart:306:20)
I/flutter (16541): #6      SendbirdSdkInternal.connect.<anonymous closure> (package:sendbird_sdk/sdk/internal/sendbird_sdk_internal.dart:283:13)
I/flutter (16541): #7      SendbirdSdkInternal.connect.<anonymous closure> (package:sendbird_sdk/sdk/internal/sendbird_sdk_internal.dart:281:66)
I/flutter (16541): #8      _rootRun (dart:async/zone.dart:1418:47)
I/flutter (16541): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
I/flutter (16541): #10     Future.timeout.<anonymous closure> (dart:async/futu
I/flutter (16541): ----------------------------------------------------
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Deleting previous websocket
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 Stop socket ping
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] ┌───────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (16541): [Sendbird][I] │ 💡 connection has been lost
I/flutter (16541): [Sendbird][I] └───────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by danieljiwonkang98** [comment]
Hello @jaymungara-solutelabs, we are currently looking over the issue. Will leave a reply on this thread after the fix is made. Thanks!

**Comment by danieljiwonkang98** [comment]
Fix has been implemented in 3.1.14
