### ISSUE TITLE
Local Caching Implementation

### ISSUE THREAD

**Issue by husein-justika** [sendbird/sendbird-sdk-flutter#38]
Halo,

Do you have any plan to implement `Local Caching` feature on this SDK ?

or is there a way to implement `Local Caching` feature on current flutter SDK ?

Thanks,
HM

**Comment by danieljiwonkang98** [comment]
Sorry for the late reply. Yes we are planning to implement `Local Caching` feature later in the future but not sure when. When we do include it, will leave an update. Thanks!

**Comment by Kiruel** [comment]
@danieljiwonkang98 Any news about local caching ? Thanks.
