### ISSUE TITLE
GroupChannel.markAsRead returns void instead of Future<void>

### ISSUE THREAD

**Issue by C0deZLee** [sendbird/sendbird-sdk-flutter#44]
This makes us unable to await on markAsRead, I don't think this is intended behaviour

<img width="717" alt="image" src="https://user-images.githubusercontent.com/7098849/174411116-29c2ead4-ac61-424f-8906-d8077f767c67.png">

**Comment by danieljiwonkang98** [comment]
Hello @C0deZLee, sorry for the late reply. The update will be made on the next patch SendbirdSDK v 3.1.15.
