### ISSUE TITLE
Reply and threadInfo in message story

### ISSUE THREAD

**Issue by RicharC293** [sendbird/sendbird-sdk-flutter#5]
In the implementation of reply to a specific message not show threadInfo, parentMessage is showed but if only one user reply a message threadInfo is null and not list "mostRepliesUsers"
Same problem is in "onMessageReceived" handler show parent message but threadedInfo is null

Here my code to load messages
https://gist.github.com/RicharC293/e4d42b9fe334429c839f23b09465a7c0#file-get_story_chat-dart

Sendbird SDK Version 3.0.13
Flutter doctor
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [VersiÃ³n 10.0.19042.985], locale es-EC)
    • Flutter version 1.22.6 at C:\src\flutter
    • Framework revision 9b2d32b605 (5 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\tipti\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

**Comment by intoxicated** [comment]
hi @RicharC293, I found that theres a bug that mapping json response with incorrect name. I will fix this on next patch, thanks for the report!

**Comment by intoxicated** [comment]
@RicharC293 are you using flutter 2? if so, you can install `3.0.14-nullsafety` with bug fixes you reported.
