### ISSUE TITLE
Unexpected channel last message in onMessageReceived event.

### ISSUE THREAD

**Issue by MrLepage** [sendbird/sendbird-sdk-flutter#6]
In the `onMessageReceived` event of the `ChannelEventHandler`, I expect the given channel object to have the received message as `lastMessage`.

That is not the case.

Is it an expected behaviour ?
In the React library, the channel in the `onMessageReceived` event of the `ChannelEventHandler` as the received message as `lastMessage`.

**Comment by intoxicated** [comment]
@MrLepage do you experience channel's last message is not updated every time you receive a new message?

**Comment by intoxicated** [comment]
I see, I think that was intended because `channelChanged` callback is right place when last message is set for channel object. Let me talk with my teams and I will let you know

**Comment by intoxicated** [comment]
@MrLepage will fix this issue on next prerelease version (with nullsafety). Thanks for the report!

**Comment by intoxicated** [comment]
the fixed has been included in `3.1.0-nullsafety`
