### ISSUE TITLE
User in muted/unmuted event instead of Member ?

### ISSUE THREAD

**Issue by MrLepage** [sendbird/sendbird-sdk-flutter#8]
I expect to have a `Member` with the updated muted status in mute and unmute events.

![image](https://user-images.githubusercontent.com/18703480/124137398-f15f6b00-da85-11eb-8235-a81a7f92c8a3.png)

**Comment by intoxicated** [comment]
We only provide `User` object both `onUserMuted` and `onUserUnmuted` case at the moment. Its same across all platforms.

**Comment by intoxicated** [comment]
feel free to reopen if you have any questions regard this matter
